### ISSUE TITLE
Scaling and Performance

### ISSUE THREAD

**Issue by LaurenceRawlings** [LaurenceRawlings/filevault#12]
## Tasks
- Configure metrics tooling and monitoring for App.
- Setting up auto-scaling in cloud environments.
- Performance testing and optimisation.
- Cost management and optimisation.

## Acceptance Criteria
- [ ] Metrics tooling and monitoring for application configured.
- [ ] Auto-scaling set up in cloud environments.
- [ ] Performance testing and optimisation conducted.
