### ISSUE TITLE
Your Own Customisation

### ISSUE THREAD

**Issue by LaurenceRawlings** [LaurenceRawlings/filevault#13]
## Tasks
- Choose one feature (Serverless Functions, Cloud Authentication such as Azure Entra or AWS Cognito or Cloud Database) to implement.
- Apply the learned techniques and technologies to customise your application.
- Present the customisation and explain the implementation process.

## Acceptance Criteria
- [ ] Chosen feature implemented.
- [ ] Techniques and technologies from previous modules applied to customise the application.
- [ ] Customisation presented with a detailed explanation of the implementation process.
