### ISSUE TITLE
Version Control and Collaboration

### ISSUE THREAD

**Issue by LaurenceRawlings** [LaurenceRawlings/filevault#2]
## Tasks
- Setting up a Git repository and cloning the app into your repository  
  [https://github.com/Weapon-of-Choice/filevault](https://github.com/Weapon-of-Choice/filevault)

## Acceptance Criteria
- [ ] Git repository set up with the forked app.
- [ ] Initial app cloned to local environment.
- [ ] Basic commits and pushes demonstrated.
- [ ] Invited a reviewer from the organiser team to their repository.
- [ ] PRs created and reviewed by the organiser team.
