### ISSUE TITLE
Continuous Integration (CI)

### ISSUE THREAD

**Issue by LaurenceRawlings** [LaurenceRawlings/filevault#3]
## Tasks
- Setting up a CI pipeline using GitHub Actions, GitLab CI/Travis CI etc.
- Setting up linter checks in Pull Requests.
- Running automated tests on code commits.
- Running SonarQube testing as part of the CI pipeline.
- Ensuring high code quality through automated checks.

## Acceptance Criteria
- [ ] CI pipeline set up in their private repository.
- [ ] Linter checks integrated in Pull Requests.
- [ ] Automated tests configured and running on code commits.
