### ISSUE TITLE
Containerisation

### ISSUE THREAD

**Issue by LaurenceRawlings** [LaurenceRawlings/filevault#4]
## Tasks
- Creating a Docker file.
- Creating a Docker Compose file.
- Building and running Docker containers.

## Acceptance Criteria
- [ ] Dockerfile created for the base app.
- [ ] Docker Compose file created for multi-container setup if applicable.
- [ ] Successfully built and ran Docker containers.
