### ISSUE TITLE
Container Orchestration with Kubernetes

### ISSUE THREAD

**Issue by LaurenceRawlings** [LaurenceRawlings/filevault#6]
## Tasks
- Pulling the image from the registry.
- Orchestrating it in Kubernetes.

## Acceptance Criteria
- [ ] Kubernetes cluster set up (local or cloud-based).
- [ ] Docker images pulled from the registry and deployed to kubernetes.
- [ ] Application deployed and managed in Kubernetes.
