### ISSUE TITLE
Configuration Management (Ansible)

### ISSUE THREAD

**Issue by LaurenceRawlings** [LaurenceRawlings/filevault#8]
## Tasks
- Using Ansible in the context of the project to automate configurations.
- Configuring a CI server (self-hosted agent on the Cloud) using Ansible.
- Where possible, infuse IaC with Ansible.
- Preparing an Ansible playbook to install, pull, and deploy to the VM.

## Acceptance Criteria
- [ ] Ansible playbook created to automate configuration tasks.
- [ ] CI server configured using Ansible (self-hosted agent on the Cloud).
- [ ] Ansible used to manage configurations and deploy applications.
