### ISSUE TITLE
Continuous Deployment (CD)

### ISSUE THREAD

**Issue by LaurenceRawlings** [LaurenceRawlings/filevault#9]
## Tasks
- Updating and extending CI pipelines to include CD.
- Deploying applications to cloud environments (Azure/AWS).
- Securely manage deployment configurations and secrets using secret management resources such as git-crypt, ansible vault, key vault, or something similar.

## Acceptance Criteria
- [ ] CI pipeline extended to include CD.
- [ ] Application deployed to cloud environments (Azure/AWS).
- [ ] Secure management of deployment configurations and secrets demonstrated (using git-crypt, Ansible Vault, Azure Key Vault, etc.).
